django/API/api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('musics.urls'))
]

django/BLOG/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('', views.index),
]

django/BOARD/board/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', views.index, name='home'),
]

django/CRUD/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

django/WUNDER/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    # path('edit/<int:pk>/', views.edit, name='edit'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

django/WUNDER/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=100)
    due_date = models.DateField()

django/WUNDER/todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Todo

# Create your views here.
# https://api.telegram.org/bot/sendMessage?text=hi&chat_id=

def index(request):
    todos = Todo.objects.all()
    context = {
        'todos': todos
    }
    return render(request, 'todos/index.html', context)


def create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')
        Todo.objects.create(title=title, due_date=due_date)

        return redirect('todos:index')

    else:
        return render(request, 'todos/create.html')


def update(request, pk):
    todo = get_object_or_404(Todo, id = pk)

    if request.method == 'POST':
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')
        todo.title = title
        todo.due_date = due_date

        todo.save()

        return redirect('todos:index')
    else:
        context = {
            'todo': todo
        }
        return render(request, 'todos/update.html', context)


def delete(request, pk):
    todo = get_object_or_404(Todo, id = pk)
    todo.delete()

    return redirect('todos:index')

django/WUNDER/todos/templates/todos/create.html
{% extends 'todos/base.html' %}

{% block body %}
<form action="{% url 'todos:create' %}" method="POST">
  {#% 주석 %#}
  {% csrf_token %}
  <p>할일 : </p><input type="text" name="title">
  <p>마감일 : </p><input type="date" name="due-date">
  <button type="submit">submit</button>
</form>
{% endblock %}

django/WUNDER/todos/templates/todos/index.html
{% extends 'todos/base.html' %}

{% block body %}
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">title</th>
        <th scope="col">date</th>
        <th scope="col">update</th>
        <th scope="col">del</th>
      </tr>
    </thead>
    <tbody>
      {% for todo in todos %}
      <tr>
        <th scope="row">{{ todo.id }}</th>
        <td>{{ todo.title }}</td>
        <td>{{ todo.due_date }}</td>
        <td><a href="{% url 'todos:update' todo.id %}">수정</a></td>
        <td><a href="{% url 'todos:delete' todo.id %}">삭제</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

django/WUNDER/todos/templates/todos/update.html
{% extends 'todos/base.html' %}

{% block body %}
<form action=" {% url 'todos:update' todo.id %}  " method="POST">
  {#% 주석 %#}
  {% csrf_token %}
  <p>할일 : </p><input type="text" name="title" value="{{todo.title}}">
  <p>마감일 : </p><input type="date" name="due-date" value="{{todo.due_date|date:'Y-m-d'}}">
  <button type="submit">submit</button>
</form>
{% endblock %}