django/API/api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('musics.urls'))
]

django/BLOG/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('', views.index),
]

django/BOARD/board/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', views.index, name='home'),
]

django/CRUD/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

django/RECAP/articles/urls.py
from django.urls import path, include
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('explore', views.explore, name='explore'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comment/', views.new_comment, name='new_comment'),
    path('<int:article_pk>/comment/<int:comment_pk>/', views.detail, name='update_comment'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete', views.delete_comment, name='delete_comment'),
    path('send_cookie/', views.send_cookie, name='send'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('tags/', views.tags, name='tags'),
    path('hashtag/<int:hashtag_pk>', views.hashtag, name='hashtag'),
]

django/BLOG/articles/models.py
from django.db import models

# Create your models here.
class ORM_Article(models.Model):
    title = models.TextField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    img_url = models.TextField()

    def __str__(self):
        return f'{self.id} : {self.title}'

django/CRUD/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.TextField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    img_url = models.TextField()

    def __str__(self):
        return f'{self.id} : {self.title}'

django/RECAP/articles/models.py
from django.db import models
from django.urls import reverse
from django.contrib import auth
from django.conf import settings

# Create your models here.


class Hashtag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
    hashtags = models.ManyToManyField(Hashtag, blank=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ('-pk',)

    #method도 추가 예정
    def get_absolute_url(self):
        return reverse('articles:detail', kwargs={'article_pk': self.pk})


class Comment(models.Model):
    content = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # article = models.ForeignKey(Article, on_delete='CASCADE')

    def __str__(self):
        return self.content

    #method도 추가 예정
    def get_absolute_url(self):
        return reverse('articles:update_comment', kwargs={'article_pk': self.article.pk, 'comment_pk': self.pk})

django/RECAP/articles/forms.py
from django import forms
from .models import Article, Comment


# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=20,
#         label='제목',
#         help_text='제목은 20글자 이내로 입력해 주세요',
#         widget=forms.TextInput(
#             attrs={
#                 'class': 'form-contral my-content',
#                 'placeholder': '제목을 입력해 주세요.',
#             }
#         )
#     )
#     content = forms.CharField(
#         label='내용',
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'form-contral my-content',
#                 'placeholder': '내용을 입력해 주세요.',
#                 'rows': 5,
#             }
#         ),
#     )


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content',)  # '__all__': 모두 다 , 이떄 자동인거 들어가면 에러에러
        # exclude = ('title',)

    # 방식 1(권장 X)
        # widgets = {
        #     # '필드(칼럼)': form속성
        #     'title': forms.TextInput(attrs={
        #                             'class': 'form-contral title-class',
        #                             'placeholder': '제목을 입력해 주세요.',
        #                             'id': 'title'
        #                         })
        # }
        # label={
        #     'title': '제목',
        # }
        # help_text={
        #     'title': '제목은 20글자 이내로 입력해 주세요',
        # }

    # 방식 2(장고 권장)
    title = forms.CharField(
        max_length=20,
        label='제목',
        help_text='제목은 20글자 이내로 입력해 주세요',
        widget=forms.TextInput(
            attrs={
                'class': 'form-contral my-content',
                'placeholder': '제목을 입력해 주세요.',
            }
        ),
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-contral my-content',
                'placeholder': '내용을 입력해 주세요.',
                'rows': 5,
            }
        ),
    )
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
    content = forms.CharField(
        label='댓글',
        widget=forms.TextInput(
            attrs={
                'class': 'form-contral my-content col-6 ml-3',
                'placeholder': '댓글을 입력해 주세요.',
                'rows': 3,
            }
        ),
    )
    # article = forms.ModelChoiceField(
    #     queryset = Article.objects.all(),
    #     label='',
        # widget=forms.ModelChoiceField(
        #     attrs={
        #         'style': 'display:none',
        #     }
        # ),
    # )

    # def __init__(self, *args, **kwargs):
    #     super(ArticleForm, self).__init__(*args, **kwargs)
    #     self.fields['article'].queryset = Article.objects.all()

django/BLOG/articles/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from .models import ORM_Article

blog_articles = []
blog_dict_articles = []
blog_class_articles = []

class Article:
    def __init__(self, title, content, created_at):
        self.title = title
        self.content = content
        self.created_at = created_at

    def __str__(self):
        return f'제목 : {self.title} 내용 : {self.content} 작성시간 : {self.created_at}'





# Create your views here.
def new(request):
    return render(request,'articles/new.html')

def create(request):
    title = request.GET.get('title')
    content = request.GET.get('content')
    img_url = request.GET.get('img_url')

    now = datetime.now

    blog_articles.append((title, content))
    blog_dict_articles.append({'title':title, 'content':content, 'created_at':now})
    blog_class_articles.append(Article(title,content,now))

    article = ORM_Article()
    article.title = title
    article.content = content
    article.img_url = img_url
    article.save()


    context = {
        'title' : title,
        'content' : content,
    }

    return redirect('index')
    # render(request, 'articles/create.html', context)


def index(request):
    articles = ORM_Article.objects.all()
    context = {
        'blog_articles' : blog_articles,
        'blog_dict_articles' : blog_dict_articles,
        'blog_class_articles' : blog_class_articles,
        'articles' : articles,
    }
    return render(request, 'articles/index.html', context)

django/CRUD/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from datetime import datetime


# Create your views here.
def new(request):
    return render(request,'articles/new.html')


def create(request):
    now = datetime.now()
    article = Article()
    article.title = request.GET.get('title')
    article.content = request.GET.get('content')
    # article.created_at = now
    article.img_url = request.GET.get('img_url')
    article.save()

    return redirect(index)


def index(request):
    all_article = reversed(Article.objects.all())
    context = {
        'articles': all_article,
    }
    return render(request,'articles/index.html',context = context)

django/RECAP/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponse, JsonResponse
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.decorators import login_required
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentForm
from itertools import chain
from IPython import embed



# Create your views here.
# @login_required
def index(request):
    # embed()
    if request.user.is_authenticated:
        # visits_num = request.session.get('visits', 0)
        # request.session['visits'] = visits_num + 1
        request.session.modified = True
        followings_and_me = chain(request.user.followings.all(), [request.user])
        articles = Article.objects.filter(user__in=followings_and_me)
    else:
        articles = Article.objects.all()

    context = {
        'articles': articles,
        # 'visits': visits_num,
    }
    return render(request, 'articles/index.html', context=context)



def explore(request):
    # embed()
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/explore.html', context=context)


def tags(request):
    # embed()
    tags = Hashtag.objects.filter()
    context = {
        'tags': tags,
    }
    return render(request, 'articles/tags.html', context=context)


def hashtag(request, hashtag_pk):
    # embed()
    hashtag = get_object_or_404(Hashtag, pk=hashtag_pk)
    articles = hashtag.article_set.all()
    context = {
        'articles': articles,
        'hashtag': hashtag,
    }
    return render(request, 'articles/hashtag.html', context=context)


# @login_required(login_url='accounts/login')
@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        
        # 데이터 유효성 검사
        if form.is_valid():
            # title = form.cleaned_data.get('title')
            # content = form.cleaned_data.get('content')
            # article = Article.objects.create(title=title, content=content)
            article = form.save(commit=False)
            article.user = request.user
            article.save()

            for word in article.content.split():
                if word.startswith('#'):
                    hashtag, created = Hashtag.objects.get_or_create(content=word)
                    article.hashtags.add(hashtag)

            return redirect(article)
        else:
            return redirect('articles:create')
    else:
        form = ArticleForm()
        context = {
            'form': form,
        }
        return render(request, 'articles/create.html', context)
        

def detail(request, article_pk, comment_pk=None):
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comment_set.all()
    commentform = CommentForm()
    # visits_num = request.session.get('visits', 0)
    # request.session['visits'] = visits_num + 1
    # request.session.modified = True
    context = {
        'article': article,
        'comments': comments,
        'commentform': commentform,
        'comment_pk': comment_pk,
    }
    if comment_pk:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user != request.user():
            return redirect(article)
        if request.method == 'POST':
            form = CommentForm(request.POST, instance=comment)
            if form.is_valid():
                new_form = form.save(commit=False)
                new_form.article = article
                new_form.user = request.user
                new_form.save()
                return redirect(article)
        else:
            form = CommentForm(instance=comment)
            context['form'] = form

    return render(request, 'articles/detail.html', context)


@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)

    if article.user != request.user:
        return redirect(article)

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        
        # 데이터 유효성 검사
        if form.is_valid():
            # article.title = form.cleaned_data.get('title')
            # article.content = form.cleaned_data.get('content')
            # article.save()
            form.save()
            return redirect(article)

    data = {
        'title': article.title,
        'content': article.content,
    }
    form = ArticleForm(instance=article)
    # form = ArticleForm(initial=data) # initial, data 사용 가능하나 data는 유저 정보를 위해 사용하자
    # form.is_valid()

    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)


@require_POST
@login_required
def delete(request, article_pk):


    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if article.user != request.user:
            return redirect(article)

        if request.method == 'POST':
            article.delete()
            return redirect('articles:index')
        else:
            return redirect(article)
    else:
        return HttpResponse('검증되지 않은 유저정보입니다.', status=401)


@require_POST
@login_required
def new_comment(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.article = Article.objects.get(pk=article_pk)
            new_form.user = request.user
            new_form.save()
            return redirect(article)
    else:
        return redirect(article)
        

@require_POST
@login_required
def delete_comment(request, article_pk, comment_pk):
    article = Article.objects.get(pk=article_pk)
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        if comment.article == article:
            comment.delete()
    return redirect(article)


def send_cookie(request):
    res = HttpResponse('과자 받아라')
    res.set_cookie('mycookie', 'oreo')
    return res


@login_required
def like(request, article_pk):
    article = get_object_or_404(Article,pk=article_pk)
    user = request.user

    if article.like_users.filter(pk=user.pk).exists():
        article.like_users.remove(user)
        liked = False

    else:
        article.like_users.add(user)
        liked = True
    # return redirect(article)
    context = {
        'liked': liked,
        'count': article.like_users.count(),
        # 'users': article.like_users.all(),
    }

    return JsonResponse(context)

django/RECAP/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block main %}
<h1>새글쓰기</h1>
{% endblock %}

{% block body %}
{% if user.is_authenticated %}
<h2>Form 클레스를 통한 HTML Form 생성</h2>

<form action="{% url 'articles:create' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">글쓰기</button>
</form>
{% else %}
<p>로그인을 먼저 해 주세요</p>
{% endif %}
{% endblock %}

django/RECAP/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block main %}
<h1>상세보기</h1>
{% endblock %}

{% block body %}
<div class="form-group">
  <h3>Title</h3>
  <h4>{{article.title}}</h4>
  <p>작성자 : {{ article.user }}</p>
</div>
<br>
<div class="form-group">
  <h5 for="content">Content</h5>
  <p></p>
  <pre>{{article.content}}</pre>
  <p>생성일 {{ article.created_at|date:"Y년 M d일"}}</p>
  <p>수정일 {{ article.updated_at|date:"Y년 M d일"}}</p>
  <!-- sort_date_format으로 간편 포멧팅 가능 -->
</div>
<h2>해쉬테그</h2>
{% with hashtags=article.hashtags.all %}
  {% for hashtag in hashtags %}
    <strong>{{ hashtag }}</strong>
  {% endfor %}
{% endwith %}

{% with likers=article.like_users.all %}
<!-- {% if user in likers %}
  <p><a href="{% url 'articles:like' article.pk %}">좋아요 취소</a></p>
{% else %}
  <p><a href="{% url 'articles:like' article.pk %}">좋아요</a></p>
{% endif %} -->

  <p><button data-id="{{ article.pk }}" class="btn btn-primary" id="like-button">좋아요</button></p>
  <p>좋아요 : <span id="like-count">{{ article.like_users.count }}</span></p>
  <p>좋아하는 사람들</p>

{% for liker in likers %}
  <p>{{ liker }}</p>
{% endfor %}

<a href="{% url 'articles:index' %}">목록보기</a>
<div class="container" style="width: 80%;">
  {% for comment in comments %}
  <div class="row">
    {% if comment.pk == comment_pk %}
    <form action="{% url 'articles:update_comment' article.pk comment.pk %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% if user == article.user %}
      <button type="submit" class="btn btn-primary">수정</button>
      {% endif %}
      <p>test</p>
    </form>
    <!-- <p>조회수 : {{ visits }}</p> -->

    {% else %}
    <div class="col-1">{{ forloop.counter }}</div>
    <div class="col-5">{{ comment.user }} - {{ comment.content }}</div>
    <div class="col-2">{{ comment.created_at | date:"y/m/d h:m" }}</div>
    <div class="col-2">{{ comment.updated_at | date:"y/m/d h:m" }}</div>
    {% if user == comment.user %}
    <form action="{% url 'articles:update_comment' article.pk comment.pk %}" method="GET">
      <button type="submit" class="btn btn-success">수정</button>
    </form>
    <form action="{% url 'articles:delete_comment' article.pk comment.pk %}" class="ml-3" method="POST">
      <button type="submit" class="btn btn-danger">삭제</button>
      {% csrf_token %}
    </form>
    {% endif %}
    {% endif %}
  </div>
  {% endfor %}
  {% if user.is_authenticated %}
  <div class="row">
    <form action="{% url 'articles:new_comment' article.pk %}" method="POST">
      {% bootstrap_form commentform %}
      {% csrf_token %}
      <button type="submit" class="btn btn-primary m-0 ml-3">생성</button>
    </form>
  </div>
  {% endif %}

{% endwith %}
</div>
<script>
  const likeButten = document.querySelector('#like-button')
  const likeCount = document.querySelector('#like-count')
  
  likeButten.addEventListener('click', function(e){
    const articleId = e.target.dataset.id
    // path('<int:article_pk>/like/', views.like, name='like'),
    axios.get(`/articles/${articleId}/like/`)
      .then(response => {
        if (response.data.liked){
          e.target.classList.add('btn-outline-primary')
          e.target.classList.remove('btn-primary')
          e.target.innerText = '좋아요 취소'

        } else {
          e.target.classList.remove('btn-outline-primary')
          e.target.classList.add('btn-primary')
          e.target.innerText = '좋아요'
        }  
        likeCount.innerText = response.data.count
      })
  })
</script>

{% endblock %}

django/RECAP/articles/templates/articles/explore.html
{% extends 'base.html' %}
{% block main %}
<h1 id="title">articles</h1>
{% endblock %}

{% block body %}

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">title</th>
      <th scope="col">작성자</th>
      <th scope="col">created_at</th>
      <th scope="col">updated_at</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{article.pk}}</th>
      <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
      <td>{{ article.user }}</a></td>
      <td>{{ article.created_at }}</td>
      <td>{{ article.updated_at }}</td>
    </tr>
    {% endfor %}

  </tbody>
</table>
<!-- all articles -->
{% endblock %}

django/RECAP/articles/templates/articles/hashtag.html
{% extends 'base.html' %}
{% block main %}
<h1 id="title">{{ hashtag }}</h1>
{% endblock %}

{% block body %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">title</th>
      <th scope="col">created_at</th>
      <th scope="col">updated_at</th>
      <th scope="col">update</th>
      <th scope="col">delete</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{ article.pk }}</th>
      <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
      <td>{{ article.created_at }}</td>
      <td>{{ article.updated_at }}</td>
      {% if user.is_authenticated %}

      <td><form action="{% url 'articles:update' article.pk %}" method="GET">
        <button type="submit" class="btn btn-success">수정</button>
      </form></td>
      <td><form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">삭제</button>
      </form></td>
      {% else %}
      <td></td>
      <td></td>
      {% endif %}
    </tr>
    {% endfor %}

  </tbody>
</table>
<!-- all articles -->
{% endblock %}

django/RECAP/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block main %}
<h1 id="title">articles</h1>
{% endblock %}

{% block body %}
{% if user.is_authenticated %}
<a class="btn btn-success" href="{% url 'articles:create' %}" method='get'>새글쓰기</a>
{% endif %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">title</th>
      <th scope="col">created_at</th>
      <th scope="col">updated_at</th>
      <th scope="col">update</th>
      <th scope="col">delete</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{article.pk}}</th>
      <td><a href="{{ article.get_absolute_url }}">{{article.title}}</a></td>
      <td>{{article.created_at}}</td>
      <td>{{article.updated_at}}</td>
      {% if user.is_authenticated %}

      <td><form action="{% url 'articles:update' article.pk %}" method="GET">
        <button type="submit" class="btn btn-success">수정</button>
      </form></td>
      <td><form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">삭제</button>
      </form></td>
      {% else %}
      <td></td>
      <td></td>
      {% endif %}
    </tr>
    {% endfor %}

  </tbody>
</table>
<!-- all articles -->
{% endblock %}

django/RECAP/articles/templates/articles/tags.html
{% extends 'base.html' %}
{% block main %}
<h1 id="title">articles</h1>
{% endblock %}

{% block body %}
  {% for tag in tags %}
    <a href="{% url 'articles:hashtag' tag.pk %}">{{ tag }}</a>
  {% endfor %}
<!-- all articles -->
{% endblock %}

django/RECAP/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block main %}
<h1>새글쓰기</h1>
{% endblock %}

{% block body %}

<form action="{% url 'articles:update' article.pk %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">수정</button>
</form>
{% endblock %}